# Generated by Django 5.2.7 on 2025-11-07 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_uz",
                    models.CharField(
                        db_index=True,
                        help_text="Name in Uzbek language",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "name_oz",
                    models.CharField(
                        db_index=True,
                        help_text="Name in Uzbek Cyrillic",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        db_index=True,
                        help_text="Name in Russian language",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        db_index=True,
                        help_text="Name in English language",
                        max_length=255,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Region",
                "verbose_name_plural": "Regions",
                "db_table": "regions",
            },
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_uz",
                    models.CharField(
                        db_index=True,
                        help_text="Name in Uzbek language",
                        max_length=255,
                    ),
                ),
                (
                    "name_oz",
                    models.CharField(
                        db_index=True,
                        help_text="Name in Uzbek Cyrillic",
                        max_length=255,
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        db_index=True,
                        help_text="Name in Russian language",
                        max_length=255,
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Name in English language",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="districts",
                        to="uzbekistan.region",
                    ),
                ),
            ],
            options={
                "verbose_name": "District",
                "verbose_name_plural": "Districts",
                "db_table": "districts",
                "unique_together": {("name_uz", "name_oz", "name_ru", "region")},
            },
        ),
        migrations.CreateModel(
            name="Village",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_uz",
                    models.CharField(
                        db_index=True,
                        help_text="Name in Uzbek language",
                        max_length=255,
                    ),
                ),
                (
                    "name_oz",
                    models.CharField(
                        db_index=True,
                        help_text="Name in Uzbek Cyrillic",
                        max_length=255,
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        db_index=True,
                        help_text="Name in Russian language",
                        max_length=255,
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="villages",
                        to="uzbekistan.district",
                    ),
                ),
            ],
            options={
                "verbose_name": "Village",
                "verbose_name_plural": "Villages",
                "db_table": "villages",
                "unique_together": {("name_uz", "name_oz", "name_ru", "district")},
            },
        ),
    ]
